### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by mickeyjohn** [kenlog/TaskProgressBar#1]
Hi @kenlog,

The plugins looks interesting. It is really good to show the visualised progress for tasks. I tried installing the plugin, add plan hours to a task and updated spent hours. My question is why it still showing 0% in the parent task? Please help explain how does this plugin work?

Thanks a lot.
John

**Comment by RainerBielefeld** [comment]
## My problem: Plugin does nothing!

## My Configuration
* KANBOARD Application version: 1.2.22 on all-inkl.com
* PHP version: 7.4.28
* PHP SAPI: fpm-fcgi
* HTTP Client: cURL
* OS version: Linux 4.15.0-177-generic
* Database driver: mysql
* Database version: 5.7.37-nmm1-log
* [Plugins](https://kanboard.org/plugins.html): [Wiki](https://github.com/funktechno/kanboard-plugin-wiki), [ProjectInvitation](https://github.com/ipunkt/KanboardProjectInvitation), [MarkdownPlus](https://github.com/creecros/MarkdownPlus),[Task2Pdf](https://github.com/creecros/Task2pdf) and [Plugin Registration v1.0.8](https://github.com/kanboard/plugin-registration/). TaskProgressBar
* Browser: **SeaMonkey** (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0)

What's going wrong here?

**Comment by kenlog** [comment]
@mickeyjohn @RainerBielefeld the advancement of the percentage corresponds you have completed subtask 

**Task**
- [x] Subtask1
- [ ] Subtask2

||||||||50%

**Comment by mickeyjohn** [comment]
@kenlog Thank you very much for the explanation. Now I know how it works ;).
